### PR TITLE
✨ (tokenlist.json): Add new token entries for BACON and BREAD tokens …

### PR DESCRIPTION
**Pull request by skullzarmy**
…with their respective details and logo URIs

📝 (logo.png): Add logo images for BACON and BREAD tokens in the token/addresses directory

### CODE REVIEW

**Comment by skullzarmy** [comment]
anything I can do to expedite merge?

**Comment by tachyswap** [comment]
we require good liquidity for the pair with WXTZ

**Comment by skullzarmy** [comment]
> we require good liquidity for the pair with WXTZ

That seems incredibly arbitrary. I have created a pool of BACON and BREAD. My intent was not to form a wXTZ LP here. These coins were formed on OG and will follow the bootstrap curve to a LP pool with wXTZ. Tachyswap pool was to allow trading between the coins, not with XTZ. 

What exactly is "good liquidity"?

**Comment by tachyswap** [comment]
> > we require good liquidity for the pair with WXTZ
> 
> That seems incredibly arbitrary. I have created a pool of BACON and BREAD. My intent was not to form a wXTZ LP here. These coins were formed on OG and will follow the bootstrap curve to a LP pool with wXTZ. Tachyswap pool was to allow trading between the coins, not with XTZ.
> 
> What exactly is "good liquidity"?

we do have some specific requirements for tokens added to our default token list.

One of our primary goals is to ensure a smooth and efficient trading experience for users. To achieve this, we require tokens to have a significant amount of liquidity, particularly with WXTZ.

We want to clarify that this is a common practice across most DEXs.

In the meantime, users can always trade your tokens directly by pasting the CA.

**Comment by skullzarmy** [comment]
I appreciate the explanation. I guess I am used to the way SpicySwap does things. You can pair any two tokens and then that pair shows in the search and eventually gets picked up as a route for swaps. Obviously this is going to have to function a bit differently.

This is a big part of our Great 'wich Switch event. https://tezoshitcoin.xyz/misc/bacon - the main idea was to onboard tezonians and have them touch the different platforms on Etherlink. This was the Tachy touch. Would you be interested in discussing if there's some middleground or something we can do that will still have them touch your site? I can easily create a swap UI and use your contract but then they have no idea its a Tachyswap service. 

Interested in your thoughts! Feel free to reach out on X if that's easier. We can close this PR.

**Comment by tachyswap** [comment]
pls join our discord & open a ticket so we can discuss more

**Pull request closed without merging**
